#we use for testing purposes the docker container of linphone-sdk
image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:9
stages:
  - build-dependencies
  - build
  - test
build-decaf:
  stage: build-dependencies
  tags: [ "docker" ] #needed for the stage to be runned
  script:
    - git clone https://gitlab.linphone.org/BC/public/external/decaf.git
    - cd decaf
    - mkdir -p build-decaf && cd build-decaf
    - cmake .. -DCMAKE_INSTALL_PREFIX=../../install
    - cmake --build . --target install
  #uploading the artifacts for the next stage    
  artifacts:
    paths:
      - install/*
    
build-mbedtls:
  stage: build-dependencies
  tags: [ "docker" ] #needed for the stage to be runned
  script:
    - git clone https://gitlab.linphone.org/BC/public/external/mbedtls.git
    - cd mbedtls
    - mkdir -p build-mbedtls && cd build-mbedtls
    - cmake .. -DCMAKE_INSTALL_PREFIX=../../install
    - cmake --build . --target install
  #uploading the artifacts for the next stage    
  artifacts:
    paths:
      - install/*
      
build-bcunit:
  stage: build-dependencies
  tags: [ "docker" ] #needed for the stage to be runned
  script:
    - git clone https://gitlab.linphone.org/BC/public/bcunit.git
    - cd bcunit
    - mkdir -p build-bcunit && cd build-bcunit
    - cmake .. -DCMAKE_INSTALL_PREFIX=../../install
    - cmake --build . --target install
  #uploading the artifacts for the next stage    
  artifacts:
    paths:
      - install/*

      
build-bctoolbox:
  stage: build
  tags: [ "docker" ] #needed for the stage to be runned
  script:
    - mkdir -p build-bctoolbox && cd build-bctoolbox
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - cmake --build . --target install
  dependencies:
    - build-decaf
    - build-mbedtls
    - build-bcunit
  #uploading the artifacts for the next stage    
  artifacts:
    paths:
      - build-bctoolbox/tester/*
      - install/*
      
test:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: test
  tags: [ "docker" ]
  
  #ugly... It's better to use a proper docker image for this istead of 
  #installing each time the container is run
  #before_script: 
   # - sudo apt-get install wget unzip
  script:
    - cd build-bctoolbox/tester
    - ./bctoolbox_tester
  dependencies:
    - build-bctoolbox
  #test artifact to add
